BEGIN TRY
	BEGIN TRANSACTION
	IF (NOT EXISTS (SELECT * 
						FROM INFORMATION_SCHEMA.TABLES 
						WHERE TABLE_SCHEMA = 'dbo' 
						AND TABLE_NAME = 'Version'))
	BEGIN
		CREATE TABLE [Version] ([Value] INT NOT NULL)
		INSERT INTO [Version] VALUES (0)

		CREATE TABLE [WorkItem] ([Id] INT identity, [NextRun] DATETIME NOT NULL, [Frequency] INT NOT NULL, [ChannelId] NVARCHAR(255) NOT NULL, [Content] NVARCHAR(MAX) NOT NULL)
		CREATE INDEX [WorkItemIndex] ON [Workitem] ([NextRun], [ChannelId])

		CREATE TABLE [ManagerRole] ([RoleId] NVARCHAR(255) PRIMARY KEY, [GuildId] NVARCHAR(255) NOT NULL)
		CREATE INDEX [ManagerRoleIndex] ON [ManagerRole] ([GuildId])
	END
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH